import type { Experience } from './experience.types';

export const experiences = [
  {
    id: 'aws-codepipeline-codebuild-multistage-delivery',
    kind: 'personal',
    title: 'Multi-stage AWS CI/CD delivery pipeline',
    summary:
      'Built AWS CodePipeline and CodeBuild automation for staging and production delivery with build validation, artifact handoff, and controlled promotion.',
    narrative: [
      'Built a delivery pipeline around AWS CodePipeline and AWS CodeBuild so application changes could move through repeatable validation before reaching runtime environments.',
      'Separated staging and production delivery concerns so changes could be exercised in a pre-production stage before production promotion, with the pipeline carrying the same build output through the release path.',
      'Used the pipeline as a reliability boundary: build feedback, deployment ordering, and environment-specific handoff were handled by automation instead of manual release steps.',
    ],
    role: 'Platform engineer',
    environments: [{ label: 'Staging' }, { label: 'Production' }],
    skillIds: [
      'aws-codepipeline',
      'aws-codebuild',
      'terraform',
      'amazon-ecr',
      'amazon-eks',
      'kubernetes',
    ],
    projectIds: ['homelab'],
    capabilityKeys: [
      'continuous-integration',
      'continuous-delivery',
      'deployment-automation',
    ],
    technologies: [
      'AWS CodePipeline',
      'AWS CodeBuild',
      'Terraform',
      'CI/CD',
    ],
    supportingEvidenceIds: [
      'terraform-codepipeline-platform',
      'codebuild-pr-gates',
      'codepipeline-approval-gated-deployment',
    ],
    isPublic: true,
  },
  {
    id: 'nx-monorepo-service-consolidation',
    kind: 'professional',
    title: 'Backend service consolidation into an Nx monorepo',
    summary:
      'Migrated standalone backend services into an Nx monorepo, consolidating duplicated services and decommissioning legacy repositories and delivery pipelines.',
    narrative: [
      'Migrated a fleet of standalone backend services into a single Nx monorepo so shared tooling, linting, testing, and build workflows could be applied uniformly instead of being maintained per repository.',
      'Consolidated duplicated services along the way, collapsing parallel implementations into single well-tested services with typed RPC interfaces and relational storage, and cut each service over environment by environment with validation at every step.',
      'Decommissioned legacy repositories, delivery pipelines, and static credentials once each migration completed, shrinking the operational surface to one delivery path per service.',
    ],
    role: 'Platform engineer',
    period: { startedAt: '2024-02' },
    environments: [{ label: 'Staging' }, { label: 'Production' }],
    skillIds: ['nx', 'typescript', 'postgresql', 'docker'],
    projectIds: [],
    capabilityKeys: [
      'version-control',
      'continuous-integration',
      'trunk-based-development',
    ],
    technologies: ['Nx', 'TypeScript', 'Node.js', 'Connect RPC', 'PostgreSQL'],
    isPublic: true,
  },
  {
    id: 'eks-platform-operations',
    kind: 'professional',
    title: 'Production Kubernetes platform operations on Amazon EKS',
    summary:
      'Operated and hardened a production Amazon EKS platform through version upgrades, capacity right-sizing, availability remediation, and managed-service migrations.',
    narrative: [
      'Operated a production Amazon EKS platform through multiple Kubernetes version upgrades and recurring maintenance cycles, keeping workloads current without service interruption.',
      'Right-sized cluster and node resources, remediated availability-zone gaps, expanded production capacity for redundancy, and moved stateful dependencies out of the cluster onto managed services.',
      'Hardened the cluster against accumulated technical debt and security risks, adding health probes and production-readiness checks across services so the platform could run multi-replica workloads reliably.',
    ],
    role: 'Platform engineer',
    period: { startedAt: '2024-02' },
    environments: [{ label: 'Production' }],
    skillIds: ['kubernetes', 'amazon-eks', 'terraform', 'helm', 'kustomize'],
    projectIds: [],
    capabilityKeys: ['flexible-infrastructure'],
    technologies: ['Amazon EKS', 'Kubernetes', 'Terraform', 'Helm', 'Kustomize'],
    isPublic: true,
  },
  {
    id: 'production-observability-stack',
    kind: 'professional',
    title: 'Production observability stack',
    summary:
      'Built out metrics, logging, error tracking, and alerting for a production platform, from service instrumentation to centralised dashboards and alert routing.',
    narrative: [
      'Built out the observability stack for a production platform: Prometheus metrics collection and Grafana dashboards for cluster and service visibility, starting from instrumenting services to export request metrics.',
      'Enabled centralised log aggregation with Loki so operational troubleshooting no longer required direct access to individual workloads, and kept the metrics and dashboard stack upgraded across major versions.',
      'Rolled out Sentry error tracking with session replay for client applications and added alerting on infrastructure saturation signals, routing alerts into team messaging so failures surface where engineers work.',
    ],
    role: 'Platform engineer',
    period: { startedAt: '2021-03' },
    environments: [{ label: 'Production' }],
    skillIds: [
      'grafana',
      'prometheus',
      'loki',
      'alertmanager',
      'alloy',
      'sentry',
    ],
    projectIds: [],
    capabilityKeys: ['monitoring-observability'],
    technologies: ['Prometheus', 'Grafana', 'Loki', 'Alertmanager', 'Sentry'],
    isPublic: true,
  },
  {
    id: 'production-reliability-engineering',
    kind: 'professional',
    title: 'Production reliability engineering',
    summary:
      'Diagnosed and eliminated recurring production failure modes, from connection exhaustion and memory leaks to silently failing jobs, and closed each with prevention.',
    narrative: [
      'Investigated and eliminated recurring production failure modes: database connection exhaustion, connection leaks in service-to-service RPC, and memory leaks that forced restarts every few days.',
      'Worked from evidence such as metrics, logs, and reproduction to attribute each failure to its source before changing systems, then fixed the root cause rather than the symptom.',
      'Closed each failure with prevention: saturation alerting, bounded resource limits, health probes tuned to real startup behaviour, and batch jobs that fail loudly instead of exiting silently.',
    ],
    role: 'Platform engineer',
    period: { startedAt: '2025-11' },
    environments: [{ label: 'Production' }],
    skillIds: ['kubernetes', 'postgresql', 'prometheus', 'grafana'],
    projectIds: [],
    capabilityKeys: ['monitoring-observability', 'deployment-automation'],
    technologies: ['Kubernetes', 'PostgreSQL', 'Prometheus', 'Grafana', 'gRPC'],
    isPublic: true,
  },
  {
    id: 'gitops-deployment-reliability',
    kind: 'professional',
    title: 'GitOps deployment reliability',
    summary:
      'Made multi-service GitOps delivery reliable with Argo CD, eliminating silent deployment skips and decoupling database migrations from service startup.',
    narrative: [
      'Improved a GitOps delivery platform built on Argo CD so every service deployment is declared, reconciled, and verifiable from version control.',
      'Made the multi-service deploy pipeline reliable by eliminating failure modes where a service could be silently skipped during release, and adopted remaining workloads into GitOps management.',
      'Decoupled database migrations from service boot with pre-sync jobs, so schema changes run as controlled deployment steps instead of racing application startup.',
    ],
    role: 'Platform engineer',
    period: { startedAt: '2026-06' },
    environments: [{ label: 'Staging' }, { label: 'Production' }],
    skillIds: ['argo-cd', 'kustomize', 'sealed-secrets', 'github-actions'],
    projectIds: [],
    capabilityKeys: ['continuous-delivery', 'deployment-automation'],
    technologies: ['Argo CD', 'Kustomize', 'Sealed Secrets', 'GitHub Actions'],
    isPublic: true,
  },
  {
    id: 'identity-access-hardening',
    kind: 'professional',
    title: 'Identity and access hardening',
    summary:
      'Hardened cloud identity and access management with scoped IAM policies, role-based access in place of static credentials, MFA, and complete offboarding.',
    narrative: [
      'Hardened cloud identity and access management: audited and scoped IAM policies, removed static credentials in favour of role-based access, and established credential-hygiene conventions for the team.',
      'Implemented engineer offboarding across cloud IAM and Kubernetes access so departures revoke access completely and promptly.',
      'Rolled out multi-factor authentication and least-privilege permission restrictions for platform users and clients, reducing the blast radius of any single compromised account.',
    ],
    role: 'Platform engineer',
    period: { startedAt: '2024-04' },
    environments: [{ label: 'Production' }],
    skillIds: ['aws-iam', 'terraform', 'kubernetes'],
    projectIds: [],
    capabilityKeys: ['pervasive-security'],
    technologies: ['AWS IAM', 'Terraform', 'Kubernetes RBAC'],
    isPublic: true,
  },
] as const satisfies readonly Experience[];
