import type { Project } from './project-list.types';

export const sampleProjects: readonly Project[] = [
  {
    id: 'dotfiles',
    title: 'benkim0414/dotfiles',
    description:
      'Cross-device macOS and Linux dotfiles managed with GNU Stow and Homebrew, covering shell, editor, terminal, agent, secret, runtime, and workflow configuration.',
    skills: [
      { label: 'GNU Stow' },
      { label: 'Homebrew' },
      { label: 'Zsh' },
      { label: 'Bash', brandLabel: 'GNU Bash' },
      { label: 'Neovim' },
      { label: 'Lua' },
      { label: 'tmux' },
      { label: 'Ghostty' },
      { label: 'bat' },
      { label: 'eza' },
      { label: 'fzf' },
      { label: 'ripgrep' },
      { label: 'Yazi' },
      { label: 'Starship' },
      { label: 'zoxide' },
      { label: 'mise' },
      { label: 'Git' },
      { label: 'delta' },
      { label: 'GitHub CLI', brandLabel: 'GitHub' },
      { label: 'gh-dash' },
      { label: 'LazyGit' },
      { label: 'SSH' },
      { label: 'Herdr' },
      { label: 'Claude Code' },
      { label: 'Codex' },
    ],
    githubUrl: 'https://github.com/benkim0414/dotfiles',
    evidenceIds: ['dotfiles-project'],
    capabilityKeys: ['developer-experience'],
  },
  {
    id: 'homelab',
    title: 'benkim0414/homelab',
    description:
      'Self-managed K3s homelab automated with Argo CD and Helm, with private networking, encrypted secrets, distributed storage, observability, databases, and off-site backups.',
    skills: [
      { label: 'K3s' },
      { label: 'Argo CD' },
      { label: 'Helm' },
      { label: 'Ansible' },
      { label: 'kubectl' },
      { label: 'Tailscale' },
      { label: 'Sealed Secrets' },
      { label: 'Traefik' },
      { label: 'Longhorn' },
      { label: 'MetalLB' },
      { label: 'kube-vip' },
      { label: 'Prometheus' },
      { label: 'Grafana' },
      { label: 'Loki' },
      { label: 'Alloy' },
      { label: 'PostgreSQL' },
      { label: 'Redis' },
      { label: 'NFS' },
      { label: 'Amazon S3' },
      { label: 'Renovate' },
    ],
    githubUrl: 'https://github.com/benkim0414/homelab',
    evidenceIds: ['homelab-project'],
    capabilityKeys: [
      'deployment-automation',
      'flexible-infrastructure',
      'monitoring-observability',
      'pervasive-security',
    ],
  },
];
