import type { Project } from './project-list.types';

export const sampleProjects: readonly Project[] = [
  {
    id: 'dotfiles',
    title: 'benkim0414/dotfiles',
    description:
      'Cross-device macOS and Linux dotfiles managed with GNU Stow and Homebrew, covering shell, editor, terminal, agent, secret, runtime, and workflow configuration.',
    skills: [
      { label: 'GNU Stow' },
      { label: 'Homebrew' },
      { label: 'Zsh' },
      { label: 'Bash', brandLabel: 'GNU Bash' },
      { label: 'Neovim' },
      { label: 'Lua' },
      { label: 'tmux' },
      { label: 'Ghostty' },
      { label: 'bat' },
      { label: 'eza' },
      { label: 'fzf' },
      { label: 'ripgrep' },
      { label: 'Yazi' },
      { label: 'Starship' },
      { label: 'zoxide' },
      { label: 'mise' },
      { label: 'Git' },
      { label: 'delta' },
      { label: 'GitHub CLI', brandLabel: 'GitHub' },
      { label: 'gh-dash' },
      { label: 'LazyGit' },
      { label: 'SSH' },
      { label: 'Herdr' },
      { label: 'Claude Code' },
      { label: 'Codex' },
    ],
    githubUrl: 'https://github.com/benkim0414/dotfiles',
    evidenceIds: ['dotfiles-project'],
    capabilityKeys: ['developer-experience'],
  },
];
