import type {
  CapabilityEvidenceItem,
  DoraCapabilityDefinition,
  DoraCapabilityScore,
  EvidenceType,
} from './devops-capability-evidence.types';

export const doraCapabilityDefinitions = [
  {
    key: 'continuous-delivery',
    label: 'Continuous Delivery',
    shortLabel: 'Delivery',
  },
  {
    key: 'deployment-automation',
    label: 'Deployment Automation',
    shortLabel: 'Deploys',
  },
  {
    key: 'continuous-integration',
    label: 'Continuous Integration',
    shortLabel: 'CI',
  },
  { key: 'test-automation', label: 'Test Automation', shortLabel: 'Tests' },
  {
    key: 'monitoring-observability',
    label: 'Monitoring and Observability',
    shortLabel: 'Observability',
  },
  {
    key: 'flexible-infrastructure',
    label: 'Flexible Infrastructure',
    shortLabel: 'Infrastructure',
  },
  {
    key: 'pervasive-security',
    label: 'Pervasive Security',
    shortLabel: 'Security',
  },
  {
    key: 'trunk-based-development',
    label: 'Trunk-Based Development',
    shortLabel: 'Trunk',
  },
  {
    key: 'documentation-quality',
    label: 'Documentation Quality',
    shortLabel: 'Docs',
  },
  {
    key: 'version-control',
    label: 'Version Control',
    shortLabel: 'Versioning',
  },
] as const satisfies readonly DoraCapabilityDefinition[];

export const curatedDevOpsCapabilityRadarScores = [
  {
    capabilityKey: 'version-control',
    label: 'Versioning',
    score: 4,
    maxScore: 5,
    evidenceIds: [
      'roadmap-repository',
      'short-lived-branch-flow',
      'protected-review-gates',
      'merge-commit-history',
    ],
    strongestEvidenceId: 'short-lived-branch-flow',
    evidenceCounts: { experience: 3, project: 1 },
  },
  {
    capabilityKey: 'trunk-based-development',
    label: 'Trunk',
    score: 4,
    maxScore: 5,
    evidenceIds: [
      'short-lived-branch-flow',
      'protected-review-gates',
      'merge-commit-history',
      'nx-affected-quality-gates',
    ],
    strongestEvidenceId: 'short-lived-branch-flow',
    evidenceCounts: { experience: 4 },
  },
  {
    capabilityKey: 'continuous-integration',
    label: 'CI',
    score: 4,
    maxScore: 5,
    evidenceIds: [
      'github-actions-ci',
      'team-delivery-workflow',
      'protected-review-gates',
      'nx-affected-quality-gates',
      'regression-gates',
    ],
    strongestEvidenceId: 'github-actions-ci',
    evidenceCounts: { experience: 5 },
  },
  {
    capabilityKey: 'test-automation',
    label: 'Tests',
    score: 3,
    maxScore: 5,
    evidenceIds: [
      'nx-affected-quality-gates',
      'jest-testcontainers-postgres',
      'regression-gates',
    ],
    strongestEvidenceId: 'jest-testcontainers-postgres',
    evidenceCounts: { experience: 3 },
  },
  {
    capabilityKey: 'pervasive-security',
    label: 'Security',
    score: 2,
    maxScore: 5,
    evidenceIds: [
      'image-digest-deployments',
      'irsa-service-accounts',
      'terraform-scoped-iam',
    ],
    strongestEvidenceId: 'irsa-service-accounts',
    evidenceCounts: { experience: 3 },
  },
  {
    capabilityKey: 'continuous-delivery',
    label: 'Delivery',
    score: 4,
    maxScore: 5,
    evidenceIds: [
      'github-actions-ci',
      'docker-delivery',
      'team-delivery-workflow',
    ],
    strongestEvidenceId: 'github-actions-ci',
    evidenceCounts: { experience: 3 },
  },
  {
    capabilityKey: 'deployment-automation',
    label: 'Deploys',
    score: 4,
    maxScore: 5,
    evidenceIds: [
      'github-actions-ci',
      'docker-delivery',
      'image-digest-deployments',
    ],
    strongestEvidenceId: 'github-actions-ci',
    evidenceCounts: { experience: 3 },
  },
  {
    capabilityKey: 'flexible-infrastructure',
    label: 'Infrastructure',
    score: 4,
    maxScore: 5,
    evidenceIds: [
      'kubernetes-workloads',
      'kubectl-troubleshooting',
      'cluster-operations',
      'cncf-kubernetes-certification',
      'kubernetes-skill',
      'irsa-service-accounts',
      'terraform-scoped-iam',
    ],
    strongestEvidenceId: 'cncf-kubernetes-certification',
    evidenceCounts: {
      certification: 1,
      experience: 2,
      learning: 3,
      skill: 1,
    },
  },
  {
    capabilityKey: 'monitoring-observability',
    label: 'Observability',
    score: 3,
    maxScore: 5,
    evidenceIds: [
      'kubectl-troubleshooting',
      'cluster-operations',
      'cncf-kubernetes-certification',
      'kubernetes-skill',
    ],
    strongestEvidenceId: 'cncf-kubernetes-certification',
    evidenceCounts: { certification: 1, learning: 2, skill: 1 },
  },
  {
    capabilityKey: 'documentation-quality',
    label: 'Docs',
    score: 4,
    maxScore: 5,
    evidenceIds: ['portfolio-radar', 'roadmap-repository'],
    strongestEvidenceId: 'portfolio-radar',
    evidenceCounts: { project: 2 },
  },
] as const satisfies readonly DoraCapabilityScore[];

export const evidenceTypeLabels = {
  skill: 'Skills',
  learning: 'Learning',
  experience: 'Experience',
  education: 'Education',
  certification: 'Certifications',
  project: 'Projects',
} as const satisfies Record<EvidenceType, string>;

export const devOpsCapabilityEvidenceItems = [
  {
    id: 'short-lived-branch-flow',
    title: 'Short-lived feature and hotfix branch flow',
    label: 'Short-lived branches',
    type: 'experience',
    organization: 'Current company',
    capabilityKeys: ['trunk-based-development', 'version-control'],
    summary:
      'Practiced short-lived feature and hotfix branches with frequent merges to keep changes small and mainline integration regular.',
    technologies: ['GitHub', 'Git'],
    isPublic: true,
    strength: 'primary',
  },
  {
    id: 'protected-review-gates',
    title: 'Protected review and status-check gates',
    label: 'Protected reviews',
    type: 'experience',
    organization: 'Current company',
    capabilityKeys: [
      'trunk-based-development',
      'continuous-integration',
      'version-control',
    ],
    summary:
      'Used protected branch rules that require passing checks and at least one human review before merging change branches.',
    technologies: ['GitHub', 'CI'],
    isPublic: true,
    strength: 'strong',
  },
  {
    id: 'merge-commit-history',
    title: 'Merge commit history preservation',
    label: 'Merge commits',
    type: 'experience',
    organization: 'Current company',
    capabilityKeys: ['trunk-based-development', 'version-control'],
    summary:
      'Used merge commits to preserve review and integration history while still keeping branches short-lived and frequently merged.',
    technologies: ['GitHub', 'Git'],
    isPublic: true,
    strength: 'supporting',
  },
  {
    id: 'nx-affected-quality-gates',
    title: 'Nx affected quality gates',
    label: 'Nx affected',
    type: 'experience',
    organization: 'Current company',
    capabilityKeys: [
      'test-automation',
      'continuous-integration',
      'trunk-based-development',
    ],
    summary:
      'Configured monorepo CI to run lint, build, test, and type-check gates for affected projects before changes are merged.',
    technologies: ['Nx', 'CI', 'TypeScript'],
    isPublic: true,
    strength: 'primary',
  },
  {
    id: 'jest-testcontainers-postgres',
    title: 'Jest and Testcontainers PostgreSQL coverage',
    label: 'Postgres tests',
    type: 'experience',
    organization: 'Current company',
    capabilityKeys: ['test-automation'],
    summary:
      'Ran microservice unit and integration tests with Jest and Testcontainers-provisioned PostgreSQL for database-backed regression coverage.',
    technologies: ['Jest', 'Testcontainers', 'PostgreSQL'],
    isPublic: true,
    strength: 'primary',
  },
  {
    id: 'regression-gates',
    title: 'Automated regression gates before merge',
    label: 'Regression gates',
    type: 'experience',
    organization: 'Current company',
    capabilityKeys: ['test-automation', 'continuous-integration'],
    summary:
      'Kept merge decisions gated on automated regression checks so changes that fail required tests are not merged.',
    technologies: ['CI', 'Jest'],
    isPublic: true,
    strength: 'primary',
  },
  {
    id: 'image-digest-deployments',
    title: 'Immutable image digest deployments',
    label: 'Image digests',
    type: 'experience',
    organization: 'Current company',
    capabilityKeys: ['pervasive-security', 'deployment-automation'],
    summary:
      'Improved deployment supply-chain safety by moving container image references from commit-hash tags to immutable image digests.',
    technologies: ['Docker', 'Kubernetes'],
    isPublic: true,
    strength: 'strong',
  },
  {
    id: 'irsa-service-accounts',
    title: 'IRSA service account migration',
    label: 'IRSA',
    type: 'experience',
    organization: 'Current company',
    capabilityKeys: ['pervasive-security', 'flexible-infrastructure'],
    summary:
      'Migrated microservice AWS access from IAM users to IRSA-backed Kubernetes service accounts for workload-scoped identity.',
    technologies: ['AWS IAM', 'IRSA', 'Kubernetes'],
    isPublic: true,
    strength: 'strong',
  },
  {
    id: 'terraform-scoped-iam',
    title: 'Terraform-managed scoped IAM policies',
    label: 'Terraform IAM',
    type: 'experience',
    organization: 'Current company',
    capabilityKeys: ['pervasive-security', 'flexible-infrastructure'],
    summary:
      'Managed IRSA service accounts and scoped IAM policies with Terraform to make microservice permissions explicit and reproducible.',
    technologies: ['Terraform', 'AWS IAM', 'Kubernetes'],
    isPublic: true,
    strength: 'strong',
  },
  {
    id: 'github-actions-ci',
    title: 'GitHub Actions CI workflow ownership',
    label: 'GitHub Actions',
    type: 'experience',
    organization: 'Current company',
    capabilityKeys: [
      'continuous-delivery',
      'deployment-automation',
      'continuous-integration',
    ],
    summary:
      'Owned GitHub Actions workflow improvements that supported continuous integration, delivery, and deployment automation.',
    technologies: ['GitHub Actions'],
    isPublic: true,
    strength: 'primary',
  },
  {
    id: 'docker-delivery',
    title: 'Docker delivery workflow support',
    label: 'Docker',
    type: 'experience',
    organization: 'Current company',
    capabilityKeys: ['continuous-delivery', 'deployment-automation'],
    summary:
      'Used Docker as part of delivery workflow evidence for packaging and deployment-oriented automation.',
    technologies: ['Docker'],
    isPublic: true,
    strength: 'strong',
  },
  {
    id: 'team-delivery-workflow',
    title: 'Small-team delivery workflow ownership',
    label: 'Team delivery',
    type: 'experience',
    organization: 'Current company',
    capabilityKeys: ['continuous-delivery', 'continuous-integration'],
    summary:
      'Owned CI/CD workflow improvements for a four-developer product team using safe public summary only.',
    technologies: ['CI', 'GitHub Actions'],
    isPublic: true,
    strength: 'strong',
  },
  {
    id: 'kubernetes-workloads',
    title: 'Kubernetes workload practice',
    label: 'Workloads',
    type: 'learning',
    date: '2026-03-01',
    endDate: '2026-04-05',
    capabilityKeys: ['flexible-infrastructure'],
    summary:
      'Practiced Kubernetes workloads and services as part of an operations-focused learning path.',
    technologies: ['Kubernetes'],
    isPublic: true,
    strength: 'strong',
  },
  {
    id: 'kubectl-troubleshooting',
    title: 'kubectl troubleshooting practice',
    label: 'kubectl',
    type: 'learning',
    date: '2026-03-01',
    endDate: '2026-04-05',
    capabilityKeys: ['flexible-infrastructure', 'monitoring-observability'],
    summary:
      'Practiced kubectl workflows and troubleshooting patterns for Kubernetes operational diagnosis.',
    technologies: ['Kubernetes', 'kubectl'],
    isPublic: true,
    strength: 'strong',
  },
  {
    id: 'cluster-operations',
    title: 'Kubernetes cluster operations practice',
    label: 'Cluster ops',
    type: 'learning',
    date: '2026-03-01',
    endDate: '2026-04-05',
    capabilityKeys: ['flexible-infrastructure', 'monitoring-observability'],
    summary:
      'Practiced Kubernetes cluster operations that connect infrastructure management with observability-oriented workflows.',
    technologies: ['Kubernetes'],
    isPublic: true,
    strength: 'strong',
  },
  {
    id: 'cncf-kubernetes-certification',
    title: 'CNCF Kubernetes certification',
    label: 'Kubernetes cert',
    type: 'certification',
    issuer: 'Cloud Native Computing Foundation',
    capabilityKeys: ['flexible-infrastructure', 'monitoring-observability'],
    summary:
      'Cloud native certification evidence mapped to Kubernetes operations and infrastructure capability.',
    technologies: ['Kubernetes'],
    isPublic: true,
    strength: 'primary',
  },
  {
    id: 'portfolio-radar',
    title: 'DevOps capability portfolio radar',
    label: 'Portfolio radar',
    type: 'project',
    proofUrl: 'https://github.com/benkim0414/benkim0414',
    capabilityKeys: ['documentation-quality'],
    summary:
      'Built a portfolio visualization that maps DevOps topics, skills, certifications, and capability evidence.',
    technologies: ['React', 'TypeScript', 'Nx'],
    isPublic: true,
    strength: 'strong',
  },
  {
    id: 'roadmap-repository',
    title: 'DevOps roadmap repository',
    label: 'Roadmap repo',
    type: 'project',
    proofUrl: 'https://github.com/benkim0414/benkim0414',
    capabilityKeys: ['documentation-quality', 'version-control'],
    summary:
      'Maintained the portfolio roadmap source in version control with structured documentation-oriented project data.',
    technologies: ['GitHub', 'TypeScript', 'Nx'],
    isPublic: true,
    strength: 'strong',
  },
  {
    id: 'kubernetes-skill',
    title: 'Kubernetes',
    type: 'skill',
    capabilityKeys: ['flexible-infrastructure', 'monitoring-observability'],
    summary:
      'Kubernetes skill shown because it is backed by learning and operations evidence.',
    technologies: ['Kubernetes'],
    isPublic: true,
    strength: 'supporting',
    supportingEvidenceIds: [
      'kubernetes-workloads',
      'kubectl-troubleshooting',
      'cluster-operations',
    ],
  },
] as const satisfies readonly CapabilityEvidenceItem[];
