import type { Skill } from './skill-list.types';

export const sampleSkills: readonly Skill[] = [
  {
    id: 'typescript',
    name: 'TypeScript',
    description: 'Typed JavaScript for building reliable applications.',
    categories: ['Language'],
    level: 5,
    iconSlug: 'typescript',
    keywords: ['javascript', 'typed', 'frontend', 'node'],
  },
  {
    id: 'react',
    name: 'React',
    description: 'Component-based UI library for interactive web interfaces.',
    categories: ['Framework'],
    level: 5,
    iconSlug: 'react',
    keywords: ['frontend', 'ui', 'components'],
  },
  {
    id: 'nx',
    name: 'Nx',
    description: 'Extensible build system for monorepos and workspaces.',
    categories: ['Build', 'Tooling'],
    level: 4,
    iconSlug: 'nx',
    keywords: ['monorepo', 'workspace', 'build system'],
  },
  {
    id: 'aws',
    name: 'AWS',
    description: 'Cloud platform for scalable infrastructure and services.',
    categories: ['Cloud'],
    level: 4,
    iconSlug: 'amazonaws',
    keywords: ['cloud', 'infrastructure'],
  },
  {
    id: 'terraform',
    name: 'Terraform',
    description: 'Infrastructure as code for provisioning cloud resources.',
    categories: ['IaC', 'Cloud'],
    level: 4,
    iconSlug: 'terraform',
    keywords: ['infrastructure as code', 'provisioning'],
  },
  {
    id: 'docker',
    name: 'Docker',
    description: 'Container platform for packaging and running applications.',
    categories: ['Container', 'Runtime'],
    level: 4,
    iconSlug: 'docker',
    keywords: ['container', 'image', 'runtime'],
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    description:
      'Container orchestration for deploying, scaling, and operating cloud-native workloads.',
    categories: ['Container', 'Cloud'],
    level: 4,
    iconSlug: 'kubernetes',
    keywords: ['containers', 'orchestration', 'platform', 'cloud native'],
    certifications: [
      {
        title: 'KCNA',
        url: 'https://example.com/kcna',
        skills: ['Kubernetes'],
        expiresAt: '2028-02-26T10:59:00+11:00',
      },
      {
        title: 'CKA',
        url: 'https://example.com/cka',
        skills: ['Kubernetes'],
        expiresAt: '2028-02-26T10:59:00+11:00',
      },
      {
        title: 'CKAD',
        url: 'https://example.com/ckad',
        skills: ['Kubernetes'],
        expiresAt: '2028-02-26T10:59:00+11:00',
      },
    ],
  },
  {
    id: 'github-actions',
    name: 'GitHub Actions',
    description: 'Automated workflows for building, testing, and deploying code.',
    categories: ['CI/CD'],
    level: 4,
    iconSlug: 'githubactions',
    keywords: ['ci', 'cd', 'automation', 'workflow'],
  },
  {
    id: 'storybook',
    name: 'Storybook',
    description: 'Development environment for building and testing UI components.',
    categories: ['Design System', 'Testing'],
    level: 4,
    iconSlug: 'storybook',
    keywords: ['components', 'ui', 'visual testing'],
  },
];
